/**
 * [PRME-INFRA-006] 基础设施
 * 文件: 001-initial-schema.ts
 * 需求描述: PRME v1.3 完整初始 schema 迁移（SQLite / PostgreSQL）
 * 最后更新: 2026-08-23
 * 
 * 本迁移根据当前 TypeORM 实体模型生成，确保全新数据库在 synchronize=false 下
 * 也能正确启动，避免开发/测试环境因 synchronize=true 掩盖的 schema 漂移问题。
 */
import { MigrationInterface, QueryRunner } from 'typeorm';
import { getDbType } from '../../utils/dbTypes';

export class InitialSchema1718000000001 implements MigrationInterface {
  name = 'InitialSchema1718000000001';

  async up(queryRunner: QueryRunner): Promise<void> {
    const dbType = getDbType();
    const isPostgres = dbType === 'postgres';

    if (!isPostgres) {
      // SQLite：关闭外键检查，允许按 TypeORM 生成顺序创建带外键约束的表
      await queryRunner.query('PRAGMA foreign_keys = OFF');
    }

    const tableDefinitions: Record<string, { sqlite: string; pg: string }> = {};

    const addTable = (name: string, sqlite: string, pg: string) => {
      tableDefinitions[name] = { sqlite, pg };
    };

    addTable('users',
      `CREATE TABLE "users" ("user_id" varchar PRIMARY KEY NOT NULL, "username" varchar(50) NOT NULL, "email" varchar(100), "phone" varchar(20), "phone_encrypted" varchar(255), "openid" varchar(64), "unionid" varchar(64), "password_hash" varchar(255), "avatar_url" varchar(255), "status" varchar(20) NOT NULL DEFAULT ('active'), "role" varchar(20) NOT NULL DEFAULT ('user'), "first_risk_acknowledged" boolean NOT NULL DEFAULT (0), "first_risk_acknowledged_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "last_login" datetime, "login_count" integer NOT NULL DEFAULT (0), "deleted_at" datetime, "deleted_by" varchar, "preferences" text NOT NULL DEFAULT ('{}'), "subscription" text NOT NULL DEFAULT ('{}'), "wechat_info" text, "metadata" text NOT NULL DEFAULT ('{}'), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "UQ_9c98f005249412c8333a3b2c593" UNIQUE ("openid"))`,
      `CREATE TABLE "users" ("user_id" varchar PRIMARY KEY NOT NULL, "username" varchar(50) NOT NULL, "email" varchar(100), "phone" varchar(20), "phone_encrypted" varchar(255), "openid" varchar(64), "unionid" varchar(64), "password_hash" varchar(255), "avatar_url" varchar(255), "status" varchar(20) NOT NULL DEFAULT ('active'), "role" varchar(20) NOT NULL DEFAULT ('user'), "first_risk_acknowledged" boolean NOT NULL DEFAULT false, "first_risk_acknowledged_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "last_login" datetime, "login_count" integer NOT NULL DEFAULT (0), "deleted_at" datetime, "deleted_by" varchar, "preferences" text NOT NULL DEFAULT ('{}'), "subscription" text NOT NULL DEFAULT ('{}'), "wechat_info" text, "metadata" text NOT NULL DEFAULT ('{}'), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "UQ_9c98f005249412c8333a3b2c593" UNIQUE ("openid"))`);

    addTable('optimization_scenarios',
      `CREATE TABLE "optimization_scenarios" ("scenario_id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "objective" varchar(30) NOT NULL, "description" text, "constraints" text, "scoring_model" text, "filter_rules" text, "backtest_period_days" integer NOT NULL DEFAULT (252), "disclaimer" text NOT NULL, "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "optimization_scenarios" ("scenario_id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "objective" varchar(30) NOT NULL, "description" text, "constraints" text, "scoring_model" text, "filter_rules" text, "backtest_period_days" integer NOT NULL DEFAULT (252), "disclaimer" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('stress_scenarios',
      `CREATE TABLE "stress_scenarios" ("scenario_id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" text, "scenario_type" varchar(20) NOT NULL, "params" text NOT NULL DEFAULT ('{}'), "historical_period_start" date, "historical_period_end" date, "historical_deviation" decimal(10,6), "is_builtin" boolean NOT NULL DEFAULT (0), "created_by" varchar, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime)`,
      `CREATE TABLE "stress_scenarios" ("scenario_id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" text, "scenario_type" varchar(20) NOT NULL, "params" text NOT NULL DEFAULT ('{}'), "historical_period_start" date, "historical_period_end" date, "historical_deviation" decimal(10,6), "is_builtin" boolean NOT NULL DEFAULT false, "created_by" varchar, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime)`);

    addTable('help_content',
      `CREATE TABLE "help_content" ("content_id" varchar PRIMARY KEY NOT NULL, "topic" varchar(50) NOT NULL, "category" varchar(20) NOT NULL DEFAULT ('general'), "status" varchar(20) NOT NULL DEFAULT ('published'), "tags" text, "format" varchar(20) NOT NULL DEFAULT ('markdown'), "title" varchar(200) NOT NULL, "content" text NOT NULL, "content_type" varchar(20) NOT NULL DEFAULT ('markdown'), "video_url" varchar(500), "video_id" varchar, "thumbnail_url" varchar(500), "duration" integer, "images" text, "sort_order" integer NOT NULL DEFAULT (0), "related_topics" text, "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime, CONSTRAINT "UQ_1a409f09bdc0d43788bb39af2de" UNIQUE ("topic"))`,
      `CREATE TABLE "help_content" ("content_id" varchar PRIMARY KEY NOT NULL, "topic" varchar(50) NOT NULL, "category" varchar(20) NOT NULL DEFAULT ('general'), "status" varchar(20) NOT NULL DEFAULT ('published'), "tags" text, "format" varchar(20) NOT NULL DEFAULT ('markdown'), "title" varchar(200) NOT NULL, "content" text NOT NULL, "content_type" varchar(20) NOT NULL DEFAULT ('markdown'), "video_url" varchar(500), "video_id" varchar, "thumbnail_url" varchar(500), "duration" integer, "images" text, "sort_order" integer NOT NULL DEFAULT (0), "related_topics" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime, CONSTRAINT "UQ_1a409f09bdc0d43788bb39af2de" UNIQUE ("topic"))`);

    addTable('market_risk_alerts',
      `CREATE TABLE "market_risk_alerts" ("alert_id" varchar PRIMARY KEY NOT NULL, "index_symbol" varchar(20) NOT NULL, "index_name" varchar(50) NOT NULL, "previous_close" decimal(18,4) NOT NULL, "current_close" decimal(18,4) NOT NULL, "change_percentage" decimal(10,6) NOT NULL, "title" varchar(200) NOT NULL, "message" text NOT NULL, "pushed_count" integer NOT NULL DEFAULT (0), "acknowledged_count" integer NOT NULL DEFAULT (0), "triggered_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "market_risk_alerts" ("alert_id" varchar PRIMARY KEY NOT NULL, "index_symbol" varchar(20) NOT NULL, "index_name" varchar(50) NOT NULL, "previous_close" decimal(18,4) NOT NULL, "current_close" decimal(18,4) NOT NULL, "change_percentage" decimal(10,6) NOT NULL, "title" varchar(200) NOT NULL, "message" text NOT NULL, "pushed_count" integer NOT NULL DEFAULT (0), "acknowledged_count" integer NOT NULL DEFAULT (0), "triggered_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('market_risk_alert_templates',
      `CREATE TABLE "market_risk_alert_templates" ("template_id" varchar PRIMARY KEY NOT NULL, "index_symbol" varchar(20) NOT NULL, "index_name" varchar(50) NOT NULL, "title_template" varchar(200) NOT NULL, "message_template" text NOT NULL, "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "market_risk_alert_templates" ("template_id" varchar PRIMARY KEY NOT NULL, "index_symbol" varchar(20) NOT NULL, "index_name" varchar(50) NOT NULL, "title_template" varchar(200) NOT NULL, "message_template" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('anonymization_logs',
      `CREATE TABLE "anonymization_logs" ("log_id" varchar PRIMARY KEY NOT NULL, "table_name" varchar(50) NOT NULL, "records_processed" integer NOT NULL, "anonymization_type" varchar(20) NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('running'), "error_message" text, "started_at" datetime NOT NULL, "completed_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "anonymization_logs" ("log_id" varchar PRIMARY KEY NOT NULL, "table_name" varchar(50) NOT NULL, "records_processed" integer NOT NULL, "anonymization_type" varchar(20) NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('running'), "error_message" text, "started_at" datetime NOT NULL, "completed_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('audit_log_integrity',
      `CREATE TABLE "audit_log_integrity" ("integrity_id" varchar PRIMARY KEY NOT NULL, "log_id" varchar NOT NULL, "log_hash" varchar(64) NOT NULL, "previous_hash" varchar(64) NOT NULL, "chain_root" varchar(64) NOT NULL, "chain_index" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_d3c88017b73e94570da37042d17" UNIQUE ("log_id"))`,
      `CREATE TABLE "audit_log_integrity" ("integrity_id" varchar PRIMARY KEY NOT NULL, "log_id" varchar NOT NULL, "log_hash" varchar(64) NOT NULL, "previous_hash" varchar(64) NOT NULL, "chain_root" varchar(64) NOT NULL, "chain_index" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_d3c88017b73e94570da37042d17" UNIQUE ("log_id"))`);

    addTable('user_login_history',
      `CREATE TABLE "user_login_history" ("login_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "login_type" varchar(20) NOT NULL, "ip_address" varchar(50), "user_agent" text, "device_fingerprint" varchar(100), "location" varchar(50), "is_successful" boolean NOT NULL DEFAULT (0), "failure_reason" varchar(200), "session_token_jti" varchar(50), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "user_login_history" ("login_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "login_type" varchar(20) NOT NULL, "ip_address" varchar(50), "user_agent" text, "device_fingerprint" varchar(100), "location" varchar(50), "is_successful" boolean NOT NULL DEFAULT false, "failure_reason" varchar(200), "session_token_jti" varchar(50), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('market_data',
      `CREATE TABLE "market_data" ("data_id" varchar PRIMARY KEY NOT NULL, "symbol" varchar(20) NOT NULL, "name" varchar(100), "security_type" varchar(20) NOT NULL DEFAULT ('stock'), "exchange" varchar(20), "sector" varchar(50), "industry" varchar(50), "currency" varchar(10) NOT NULL DEFAULT ('CNY'), "market_cap" decimal(18,2), "open_price" decimal(18,6), "high_price" decimal(18,6), "low_price" decimal(18,6), "close_price" decimal(18,6), "volume" decimal(18,2), "turnover" decimal(18,2), "trade_date" date NOT NULL, "trade_time" time, "metadata" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "market_data" ("data_id" varchar PRIMARY KEY NOT NULL, "symbol" varchar(20) NOT NULL, "name" varchar(100), "security_type" varchar(20) NOT NULL DEFAULT ('stock'), "exchange" varchar(20), "sector" varchar(50), "industry" varchar(50), "currency" varchar(10) NOT NULL DEFAULT ('CNY'), "market_cap" decimal(18,2), "open_price" decimal(18,6), "high_price" decimal(18,6), "low_price" decimal(18,6), "close_price" decimal(18,6), "volume" decimal(18,2), "turnover" decimal(18,2), "trade_date" date NOT NULL, "trade_time" time, "metadata" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('tool_var_history',
      `CREATE TABLE "tool_var_history" ("history_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar(36) NOT NULL, "method" varchar(50) NOT NULL, "confidence_level" decimal(10,4) NOT NULL, "time_horizon" integer NOT NULL, "monte_carlo_iterations" integer, "distribution" varchar(50), "var_value" decimal(18,4) NOT NULL, "var_percentage" decimal(10,6) NOT NULL, "expected_return" decimal(18,4), "volatility" decimal(10,6), "holdings" text, "components" text, "risk_factors" text, "random_seed" integer, "calculation_time_ms" decimal(10,3), "status" varchar(20) NOT NULL DEFAULT ('completed'), "error_message" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "tool_var_history" ("history_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar(36) NOT NULL, "method" varchar(50) NOT NULL, "confidence_level" decimal(10,4) NOT NULL, "time_horizon" integer NOT NULL, "monte_carlo_iterations" integer, "distribution" varchar(50), "var_value" decimal(18,4) NOT NULL, "var_percentage" decimal(10,6) NOT NULL, "expected_return" decimal(18,4), "volatility" decimal(10,6), "holdings" text, "components" text, "risk_factors" text, "random_seed" integer, "calculation_time_ms" decimal(10,3), "status" varchar(20) NOT NULL DEFAULT ('completed'), "error_message" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('subscription_plans',
      `CREATE TABLE "subscription_plans" ("plan_id" varchar PRIMARY KEY NOT NULL, "plan_code" varchar(50) NOT NULL, "plan_name" varchar(100) NOT NULL, "description" text, "price_monthly" decimal(10,2), "price_yearly" decimal(10,2), "currency" varchar(10) NOT NULL DEFAULT ('CNY'), "features" text NOT NULL DEFAULT ('[]'), "quotas" text NOT NULL DEFAULT ('{}'), "status" varchar(20) NOT NULL DEFAULT ('active'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_3679d2313bfaf654eb1bc25eae2" UNIQUE ("plan_code"))`,
      `CREATE TABLE "subscription_plans" ("plan_id" varchar PRIMARY KEY NOT NULL, "plan_code" varchar(50) NOT NULL, "plan_name" varchar(100) NOT NULL, "description" text, "price_monthly" decimal(10,2), "price_yearly" decimal(10,2), "currency" varchar(10) NOT NULL DEFAULT ('CNY'), "features" text NOT NULL DEFAULT ('[]'), "quotas" text NOT NULL DEFAULT ('{}'), "status" varchar(20) NOT NULL DEFAULT ('active'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_3679d2313bfaf654eb1bc25eae2" UNIQUE ("plan_code"))`);

    addTable('system_configs',
      `CREATE TABLE "system_configs" ("config_id" varchar PRIMARY KEY NOT NULL, "config_key" varchar(100) NOT NULL, "config_value" text NOT NULL, "config_type" varchar(20) NOT NULL DEFAULT ('system'), "description" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_8430d4ebdc1faef3d3eeef36e87" UNIQUE ("config_key"))`,
      `CREATE TABLE "system_configs" ("config_id" varchar PRIMARY KEY NOT NULL, "config_key" varchar(100) NOT NULL, "config_value" text NOT NULL, "config_type" varchar(20) NOT NULL DEFAULT ('system'), "description" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_8430d4ebdc1faef3d3eeef36e87" UNIQUE ("config_key"))`);

    addTable('stocks',
      `CREATE TABLE "stocks" ("stock_id" varchar PRIMARY KEY NOT NULL, "symbol" varchar(20) NOT NULL, "name" varchar(100) NOT NULL, "exchange" varchar(10), "industry" varchar(50), "sector" varchar(50), "market_cap" decimal(18,2), "status" varchar(20) NOT NULL DEFAULT ('active'), "metadata" text NOT NULL DEFAULT ('{}'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_abdd997b009437486baf7531854" UNIQUE ("symbol"))`,
      `CREATE TABLE "stocks" ("stock_id" varchar PRIMARY KEY NOT NULL, "symbol" varchar(20) NOT NULL, "name" varchar(100) NOT NULL, "exchange" varchar(10), "industry" varchar(50), "sector" varchar(50), "market_cap" decimal(18,2), "status" varchar(20) NOT NULL DEFAULT ('active'), "metadata" text NOT NULL DEFAULT ('{}'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_abdd997b009437486baf7531854" UNIQUE ("symbol"))`);

    addTable('partition_metadata',
      `CREATE TABLE "partition_metadata" ("metadata_id" varchar PRIMARY KEY NOT NULL, "table_type" varchar(50) NOT NULL, "partition_name" varchar(20) NOT NULL, "partition_start" date NOT NULL, "partition_end" date NOT NULL, "record_count" bigint NOT NULL DEFAULT (0), "status" varchar(20) NOT NULL DEFAULT ('active'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "archived_at" datetime)`,
      `CREATE TABLE "partition_metadata" ("metadata_id" varchar PRIMARY KEY NOT NULL, "table_type" varchar(50) NOT NULL, "partition_name" varchar(20) NOT NULL, "partition_start" date NOT NULL, "partition_end" date NOT NULL, "record_count" bigint NOT NULL DEFAULT (0), "status" varchar(20) NOT NULL DEFAULT ('active'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "archived_at" datetime)`);

    addTable('computation_cache',
      `CREATE TABLE "computation_cache" ("cache_key" text PRIMARY KEY NOT NULL, "result_json" text NOT NULL, "computation_type" varchar(50) NOT NULL, "param_hash" text NOT NULL, "computed_at" integer NOT NULL, "expires_at" integer NOT NULL, "hit_count" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "computation_cache" ("cache_key" text PRIMARY KEY NOT NULL, "result_json" text NOT NULL, "computation_type" varchar(50) NOT NULL, "param_hash" text NOT NULL, "computed_at" integer NOT NULL, "expires_at" integer NOT NULL, "hit_count" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('market_snapshot_cache',
      `CREATE TABLE "market_snapshot_cache" ("symbol" varchar(20) NOT NULL, "snapshot_type" varchar(20) NOT NULL, "data_json" text NOT NULL, "fetched_at" integer NOT NULL, "expires_at" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("symbol", "snapshot_type"))`,
      `CREATE TABLE "market_snapshot_cache" ("symbol" varchar(20) NOT NULL, "snapshot_type" varchar(20) NOT NULL, "data_json" text NOT NULL, "fetched_at" integer NOT NULL, "expires_at" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("symbol", "snapshot_type"))`);

    addTable('portfolio_summary_cache',
      `CREATE TABLE "portfolio_summary_cache" ("portfolio_id" varchar PRIMARY KEY NOT NULL, "summary_json" text NOT NULL, "total_market_value" decimal(18,6), "var_95_1d" decimal(18,6), "max_drawdown" decimal(18,6), "updated_at" integer NOT NULL, "expires_at" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "portfolio_summary_cache" ("portfolio_id" varchar PRIMARY KEY NOT NULL, "summary_json" text NOT NULL, "total_market_value" decimal(18,6), "var_95_1d" decimal(18,6), "max_drawdown" decimal(18,6), "updated_at" integer NOT NULL, "expires_at" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('message_queue',
      `CREATE TABLE "message_queue" ("message_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "queue_name" varchar(50) NOT NULL, "payload" text NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('pending'), "priority" integer NOT NULL DEFAULT (5), "attempt_count" integer NOT NULL DEFAULT (0), "max_attempts" integer NOT NULL DEFAULT (3), "scheduled_at" integer NOT NULL, "created_at" integer NOT NULL DEFAULT (0), "processed_at" integer, "completed_at" integer, "error_message" text)`,
      `CREATE TABLE "message_queue" ("message_id" SERIAL PRIMARY KEY NOT NULL, "queue_name" varchar(50) NOT NULL, "payload" text NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('pending'), "priority" integer NOT NULL DEFAULT (5), "attempt_count" integer NOT NULL DEFAULT (0), "max_attempts" integer NOT NULL DEFAULT (3), "scheduled_at" integer NOT NULL, "created_at" integer NOT NULL DEFAULT (0), "processed_at" integer, "completed_at" integer, "error_message" text)`);

    addTable('refresh_token_blacklist',
      `CREATE TABLE "refresh_token_blacklist" ("token_jti" varchar(255) PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "revoked_at" integer NOT NULL, "expires_at" integer NOT NULL, "reason" varchar(50), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "refresh_token_blacklist" ("token_jti" varchar(255) PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "revoked_at" integer NOT NULL, "expires_at" integer NOT NULL, "reason" varchar(50), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('risk_event_sources',
      `CREATE TABLE "risk_event_sources" ("source_id" varchar PRIMARY KEY NOT NULL, "source_type" varchar(30) NOT NULL, "provider" varchar(50) NOT NULL, "name" varchar(100) NOT NULL, "config" text, "is_active" boolean NOT NULL DEFAULT (1), "last_fetch_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "risk_event_sources" ("source_id" varchar PRIMARY KEY NOT NULL, "source_type" varchar(30) NOT NULL, "provider" varchar(50) NOT NULL, "name" varchar(100) NOT NULL, "config" text, "is_active" boolean NOT NULL DEFAULT true, "last_fetch_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('market_volatility_indices',
      `CREATE TABLE "market_volatility_indices" ("index_id" varchar PRIMARY KEY NOT NULL, "index_symbol" varchar(20) NOT NULL, "index_name" varchar(100) NOT NULL, "weight" decimal(5,4) NOT NULL DEFAULT (0), "source" varchar(50), "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_8b368eb3887e80819ad9db2bf45" UNIQUE ("index_symbol"))`,
      `CREATE TABLE "market_volatility_indices" ("index_id" varchar PRIMARY KEY NOT NULL, "index_symbol" varchar(20) NOT NULL, "index_name" varchar(100) NOT NULL, "weight" decimal(5,4) NOT NULL DEFAULT (0), "source" varchar(50), "is_active" boolean NOT NULL DEFAULT true, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_8b368eb3887e80819ad9db2bf45" UNIQUE ("index_symbol"))`);

    addTable('market_volatility_history',
      `CREATE TABLE "market_volatility_history" ("history_id" varchar PRIMARY KEY NOT NULL, "index_symbol" varchar(20) NOT NULL, "volatility" decimal(10,6) NOT NULL, "percentile" decimal(5,4), "calculation_date" date NOT NULL, "calculation_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "data_points" integer NOT NULL DEFAULT (252), CONSTRAINT "UQ_21796121a4b0302dc2ab95006a1" UNIQUE ("index_symbol", "calculation_date"))`,
      `CREATE TABLE "market_volatility_history" ("history_id" varchar PRIMARY KEY NOT NULL, "index_symbol" varchar(20) NOT NULL, "volatility" decimal(10,6) NOT NULL, "percentile" decimal(5,4), "calculation_date" date NOT NULL, "calculation_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "data_points" integer NOT NULL DEFAULT (252), CONSTRAINT "UQ_21796121a4b0302dc2ab95006a1" UNIQUE ("index_symbol", "calculation_date"))`);

    addTable('portfolio_templates',
      `CREATE TABLE "portfolio_templates" ("template_id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" text, "risk_level" varchar(20) NOT NULL, "asset_allocation" text NOT NULL, "sector_allocation" text, "sample_holdings" text, "base_total_value" decimal(18,4) NOT NULL DEFAULT (100000), "disclaimer" text NOT NULL, "is_builtin" boolean NOT NULL DEFAULT (1), "is_active" boolean NOT NULL DEFAULT (1), "sort_order" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "portfolio_templates" ("template_id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" text, "risk_level" varchar(20) NOT NULL, "asset_allocation" text NOT NULL, "sector_allocation" text, "sample_holdings" text, "base_total_value" decimal(18,4) NOT NULL DEFAULT (100000), "disclaimer" text NOT NULL, "is_builtin" boolean NOT NULL DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('video_tutorials',
      `CREATE TABLE "video_tutorials" ("video_id" varchar PRIMARY KEY NOT NULL, "topic" varchar(50) NOT NULL, "title" varchar(200) NOT NULL, "description" text, "video_url" varchar(500) NOT NULL, "duration" integer, "thumbnail_url" varchar(500), "category" varchar(50) NOT NULL DEFAULT ('tutorial'), "tags" text, "sort_order" integer NOT NULL DEFAULT (0), "watch_count" integer NOT NULL DEFAULT (0), "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
      `CREATE TABLE "video_tutorials" ("video_id" varchar PRIMARY KEY NOT NULL, "topic" varchar(50) NOT NULL, "title" varchar(200) NOT NULL, "description" text, "video_url" varchar(500) NOT NULL, "duration" integer, "thumbnail_url" varchar(500), "category" varchar(50) NOT NULL DEFAULT ('tutorial'), "tags" text, "sort_order" integer NOT NULL DEFAULT (0), "watch_count" integer NOT NULL DEFAULT (0), "is_active" boolean NOT NULL DEFAULT true, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP)`);

    addTable('monitor_configs',
      `CREATE TABLE "monitor_configs" ("config_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "config_name" varchar(100) NOT NULL, "monitor_type" varchar(20) NOT NULL, "threshold" decimal(18,6) NOT NULL, "operator" varchar(10) NOT NULL DEFAULT ('>'), "metrics" text NOT NULL DEFAULT ('{}'), "check_interval_seconds" integer NOT NULL DEFAULT (30), "status" varchar(20) NOT NULL DEFAULT ('active'), "notification" text NOT NULL DEFAULT ('{}'), "rules" text NOT NULL DEFAULT ('{}'), "cooling_period_minutes" integer NOT NULL DEFAULT (5), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "last_triggered" datetime, "trigger_count" integer NOT NULL DEFAULT (0), CONSTRAINT "FK_65f241b3a10d5a8434e36094df3" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7eb986ad5f06622a671abe0a8f0" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "monitor_configs" ("config_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "config_name" varchar(100) NOT NULL, "monitor_type" varchar(20) NOT NULL, "threshold" decimal(18,6) NOT NULL, "operator" varchar(10) NOT NULL DEFAULT ('>'), "metrics" text NOT NULL DEFAULT ('{}'), "check_interval_seconds" integer NOT NULL DEFAULT (30), "status" varchar(20) NOT NULL DEFAULT ('active'), "notification" text NOT NULL DEFAULT ('{}'), "rules" text NOT NULL DEFAULT ('{}'), "cooling_period_minutes" integer NOT NULL DEFAULT (5), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "last_triggered" datetime, "trigger_count" integer NOT NULL DEFAULT (0), CONSTRAINT "FK_65f241b3a10d5a8434e36094df3" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7eb986ad5f06622a671abe0a8f0" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('alert_history',
      `CREATE TABLE "alert_history" ("history_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "rule_id" varchar, "user_id" varchar NOT NULL, "alert_type" varchar(20) NOT NULL, "severity" varchar(20) NOT NULL, "title" varchar(200) NOT NULL, "message" text, "trigger_details" text NOT NULL DEFAULT ('{}'), "notification_status" text NOT NULL DEFAULT ('{}'), "triggered_at" datetime NOT NULL, "resolved_at" datetime, "status" varchar(20) NOT NULL DEFAULT ('active'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "notification_latency_ms" integer, CONSTRAINT "FK_3245cf316413416555589fcfcea" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_95048d503befe40e467d550713a" FOREIGN KEY ("rule_id") REFERENCES "monitor_configs" ("config_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4a9060d197d1bfbf6a1c2b09d9d" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "alert_history" ("history_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "rule_id" varchar, "user_id" varchar NOT NULL, "alert_type" varchar(20) NOT NULL, "severity" varchar(20) NOT NULL, "title" varchar(200) NOT NULL, "message" text, "trigger_details" text NOT NULL DEFAULT ('{}'), "notification_status" text NOT NULL DEFAULT ('{}'), "triggered_at" datetime NOT NULL, "resolved_at" datetime, "status" varchar(20) NOT NULL DEFAULT ('active'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "notification_latency_ms" integer, CONSTRAINT "FK_3245cf316413416555589fcfcea" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_95048d503befe40e467d550713a" FOREIGN KEY ("rule_id") REFERENCES "monitor_configs" ("config_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4a9060d197d1bfbf6a1c2b09d9d" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('orders',
      `CREATE TABLE "orders" ("order_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "plan_id" varchar, "order_no" varchar(100) NOT NULL, "order_type" varchar(20) NOT NULL DEFAULT ('subscription'), "amount" decimal(10,2) NOT NULL, "currency" varchar(10) NOT NULL DEFAULT ('CNY'), "discount_amount" decimal(10,2) NOT NULL DEFAULT (0), "final_amount" decimal(10,2) NOT NULL, "payment_method" varchar(20) NOT NULL DEFAULT ('wechat'), "payment_status" varchar(20) NOT NULL DEFAULT ('pending'), "paid_at" datetime, "payment_details" text, "period_start" date, "period_end" date, "refund_info" text, "status" varchar(20) NOT NULL DEFAULT ('active'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_035026a83bef9740d7ad05df383" UNIQUE ("order_no"), CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "orders" ("order_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "plan_id" varchar, "order_no" varchar(100) NOT NULL, "order_type" varchar(20) NOT NULL DEFAULT ('subscription'), "amount" decimal(10,2) NOT NULL, "currency" varchar(10) NOT NULL DEFAULT ('CNY'), "discount_amount" decimal(10,2) NOT NULL DEFAULT (0), "final_amount" decimal(10,2) NOT NULL, "payment_method" varchar(20) NOT NULL DEFAULT ('wechat'), "payment_status" varchar(20) NOT NULL DEFAULT ('pending'), "paid_at" datetime, "payment_details" text, "period_start" date, "period_end" date, "refund_info" text, "status" varchar(20) NOT NULL DEFAULT ('active'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_035026a83bef9740d7ad05df383" UNIQUE ("order_no"), CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('user_sessions',
      `CREATE TABLE "user_sessions" ("session_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "token" varchar(255) NOT NULL, "refresh_token" varchar(255), "device_info" text, "status" varchar(20) NOT NULL DEFAULT ('active'), "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "last_active_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "UQ_ff5db00dec0f61218cd0d468df0" UNIQUE ("token"), CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "user_sessions" ("session_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "token" varchar(255) NOT NULL, "refresh_token" varchar(255), "device_info" text, "status" varchar(20) NOT NULL DEFAULT ('active'), "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "last_active_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "UQ_ff5db00dec0f61218cd0d468df0" UNIQUE ("token"), CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('audit_logs',
      `CREATE TABLE "audit_logs" ("log_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar, "operation_type" varchar(50) NOT NULL, "resource_type" varchar(50) NOT NULL, "resource_id" varchar, "details" text NOT NULL DEFAULT ('{}'), "ip_address" varchar(50), "user_agent" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "audit_logs" ("log_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar, "operation_type" varchar(50) NOT NULL, "resource_type" varchar(50) NOT NULL, "resource_id" varchar, "details" text NOT NULL DEFAULT ('{}'), "ip_address" varchar(50), "user_agent" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('holdings',
      `CREATE TABLE "holdings" ("holding_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "symbol" varchar(20) NOT NULL, "name" varchar(100), "security_type" varchar(20) NOT NULL DEFAULT ('stock'), "exchange" varchar(20), "quantity" decimal(18,6) NOT NULL DEFAULT (0), "cost_price" decimal(18,6) NOT NULL DEFAULT (0), "current_price" decimal(18,6), "market_value" decimal(18,6), "weight" decimal(10,4), "weight_target" decimal(10,4), "unrealized_pnl" decimal(18,6), "realized_pnl" decimal(18,6), "sector" varchar(50), "industry" varchar(50), "region" varchar(50), "currency" varchar(10) NOT NULL DEFAULT ('CNY'), "status" varchar(20) NOT NULL DEFAULT ('active'), "metadata" text, "import_row_id" varchar, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_2f4f9915c4b755588d01fee50be" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "holdings" ("holding_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "symbol" varchar(20) NOT NULL, "name" varchar(100), "security_type" varchar(20) NOT NULL DEFAULT ('stock'), "exchange" varchar(20), "quantity" decimal(18,6) NOT NULL DEFAULT (0), "cost_price" decimal(18,6) NOT NULL DEFAULT (0), "current_price" decimal(18,6), "market_value" decimal(18,6), "weight" decimal(10,4), "weight_target" decimal(10,4), "unrealized_pnl" decimal(18,6), "realized_pnl" decimal(18,6), "sector" varchar(50), "industry" varchar(50), "region" varchar(50), "currency" varchar(10) NOT NULL DEFAULT ('CNY'), "status" varchar(20) NOT NULL DEFAULT ('active'), "metadata" text, "import_row_id" varchar, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_2f4f9915c4b755588d01fee50be" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('var_calculations',
      `CREATE TABLE "var_calculations" ("var_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "calculation_type" varchar(20) NOT NULL, "confidence_level" decimal(5,4) NOT NULL, "time_horizon" integer NOT NULL, "distribution" varchar(20), "monte_carlo_iterations" integer, "random_seed" integer, "var_value" decimal(18,6) NOT NULL, "var_percentage" decimal(10,4), "expected_return" decimal(18,6), "expected_shortfall" decimal(18,6), "volatility" decimal(18,6), "calculation_time_ms" integer, "var_components" text NOT NULL DEFAULT ('[]'), "risk_factors" text NOT NULL DEFAULT ('[]'), "status" varchar(20) NOT NULL DEFAULT ('completed'), "error_message" text, "data_source" varchar(50), "data_period" varchar(20), "estimation_method" varchar(10), "evt_parameters" text, "warnings" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "calculated_at" datetime, CONSTRAINT "CHK_confidence_level" CHECK (confidence_level BETWEEN 0.90 AND 0.9999), CONSTRAINT "CHK_time_horizon" CHECK (time_horizon BETWEEN 1 AND 365), CONSTRAINT "FK_d200eb3c48f8e64151b36d68d40" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_59661baadd9784cf3d8c445efca" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "var_calculations" ("var_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "calculation_type" varchar(20) NOT NULL, "confidence_level" decimal(5,4) NOT NULL, "time_horizon" integer NOT NULL, "distribution" varchar(20), "monte_carlo_iterations" integer, "random_seed" integer, "var_value" decimal(18,6) NOT NULL, "var_percentage" decimal(10,4), "expected_return" decimal(18,6), "expected_shortfall" decimal(18,6), "volatility" decimal(18,6), "calculation_time_ms" integer, "var_components" text NOT NULL DEFAULT ('[]'), "risk_factors" text NOT NULL DEFAULT ('[]'), "status" varchar(20) NOT NULL DEFAULT ('completed'), "error_message" text, "data_source" varchar(50), "data_period" varchar(20), "estimation_method" varchar(10), "evt_parameters" text, "warnings" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "calculated_at" datetime, CONSTRAINT "CHK_confidence_level" CHECK (confidence_level BETWEEN 0.90 AND 0.9999), CONSTRAINT "CHK_time_horizon" CHECK (time_horizon BETWEEN 1 AND 365), CONSTRAINT "FK_d200eb3c48f8e64151b36d68d40" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_59661baadd9784cf3d8c445efca" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('stress_tests',
      `CREATE TABLE "stress_tests" ("stress_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "scenario_name" varchar(100) NOT NULL, "scenario_type" varchar(20) NOT NULL DEFAULT ('historical'), "parameters" text NOT NULL DEFAULT ('{}'), "portfolio_value" decimal(18,6), "stressed_value" decimal(18,6), "loss_amount" decimal(18,6), "loss_percentage" decimal(10,4), "asset_results" text NOT NULL DEFAULT ('[]'), "risk_changes" text NOT NULL DEFAULT ('{}'), "test_date" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CHK_loss_percentage" CHECK (loss_percentage BETWEEN -100 AND 0), CONSTRAINT "FK_5cbf54ae6a565dde492cc561ed4" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "stress_tests" ("stress_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "scenario_name" varchar(100) NOT NULL, "scenario_type" varchar(20) NOT NULL DEFAULT ('historical'), "parameters" text NOT NULL DEFAULT ('{}'), "portfolio_value" decimal(18,6), "stressed_value" decimal(18,6), "loss_amount" decimal(18,6), "loss_percentage" decimal(10,4), "asset_results" text NOT NULL DEFAULT ('[]'), "risk_changes" text NOT NULL DEFAULT ('{}'), "test_date" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CHK_loss_percentage" CHECK (loss_percentage BETWEEN -100 AND 0), CONSTRAINT "FK_5cbf54ae6a565dde492cc561ed4" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('reports',
      `CREATE TABLE "reports" ("report_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "report_name" varchar(200) NOT NULL, "report_type" varchar(20) NOT NULL DEFAULT ('var'), "period_start" date, "period_end" date, "report_content" text NOT NULL DEFAULT ('{}'), "report_url" varchar(500), "file_format" varchar(10) NOT NULL DEFAULT ('pdf'), "file_size" integer, "status" varchar(20) NOT NULL DEFAULT ('generated'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "generated_at" datetime, "expires_at" datetime, CONSTRAINT "FK_7a0697cd6847b6ceadfc9a45354" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "reports" ("report_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "report_name" varchar(200) NOT NULL, "report_type" varchar(20) NOT NULL DEFAULT ('var'), "period_start" date, "period_end" date, "report_content" text NOT NULL DEFAULT ('{}'), "report_url" varchar(500), "file_format" varchar(10) NOT NULL DEFAULT ('pdf'), "file_size" integer, "status" varchar(20) NOT NULL DEFAULT ('generated'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "generated_at" datetime, "expires_at" datetime, CONSTRAINT "FK_7a0697cd6847b6ceadfc9a45354" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('portfolios',
      `CREATE TABLE "portfolios" ("portfolio_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "name" varchar(100) NOT NULL, "description" text, "type" varchar(20) NOT NULL DEFAULT ('personal'), "status" varchar(20) NOT NULL DEFAULT ('active'), "settings" text NOT NULL DEFAULT ('{}'), "statistics" text, "investment_goal" varchar(50), "risk_level" varchar(20), "template_id" varchar, "deleted_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_57fba72db5ac40768b40f0ecfa1" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "portfolios" ("portfolio_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "name" varchar(100) NOT NULL, "description" text, "type" varchar(20) NOT NULL DEFAULT ('personal'), "status" varchar(20) NOT NULL DEFAULT ('active'), "settings" text NOT NULL DEFAULT ('{}'), "statistics" text, "investment_goal" varchar(50), "risk_level" varchar(20), "template_id" varchar, "deleted_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_57fba72db5ac40768b40f0ecfa1" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('optimization_results',
      `CREATE TABLE "optimization_results" ("optimization_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar(36) NOT NULL, "user_id" varchar(36) NOT NULL, "method" varchar(50) NOT NULL, "objective_detail" varchar(30), "scoring_model" varchar(50), "filter_rules" text, "backtest_scenario_id" varchar, "backtest_metrics" text, "current_portfolio" text, "optimized_portfolio" text, "suggestions" text, "backtest_data" text, "disclaimer" text, "compliance_note" text, "risk_constraints" text, "has_investment_keywords" boolean NOT NULL DEFAULT (0), "status" varchar(20) NOT NULL DEFAULT ('completed'), "error_message" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_3f73a5e0905a80144ee6b9f9597" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "optimization_results" ("optimization_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar(36) NOT NULL, "user_id" varchar(36) NOT NULL, "method" varchar(50) NOT NULL, "objective_detail" varchar(30), "scoring_model" varchar(50), "filter_rules" text, "backtest_scenario_id" varchar, "backtest_metrics" text, "current_portfolio" text, "optimized_portfolio" text, "suggestions" text, "backtest_data" text, "disclaimer" text, "compliance_note" text, "risk_constraints" text, "has_investment_keywords" boolean NOT NULL DEFAULT false, "status" varchar(20) NOT NULL DEFAULT ('completed'), "error_message" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_3f73a5e0905a80144ee6b9f9597" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('var_components',
      `CREATE TABLE "var_components" ("component_id" varchar PRIMARY KEY NOT NULL, "var_id" varchar NOT NULL, "symbol" varchar(20) NOT NULL, "contribution" decimal(18,4) NOT NULL, "percentage" decimal(10,6) NOT NULL, "risk_factor" varchar(50), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_c4f0c0484ab699dd60bea016022" FOREIGN KEY ("var_id") REFERENCES "var_calculations" ("var_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "var_components" ("component_id" varchar PRIMARY KEY NOT NULL, "var_id" varchar NOT NULL, "symbol" varchar(20) NOT NULL, "contribution" decimal(18,4) NOT NULL, "percentage" decimal(10,6) NOT NULL, "risk_factor" varchar(50), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_c4f0c0484ab699dd60bea016022" FOREIGN KEY ("var_id") REFERENCES "var_calculations" ("var_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('user_consents',
      `CREATE TABLE "user_consents" ("consent_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "consent_type" varchar(50) NOT NULL, "consent_version" varchar(20) NOT NULL, "consent_text_hash" varchar(64) NOT NULL, "granted_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "granted_via" varchar(20) NOT NULL, "ip_address" varchar(45), "revoked_at" datetime, "revoked_reason" text, "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_6283f1222bdc2390cf16836ce7d" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "user_consents" ("consent_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "consent_type" varchar(50) NOT NULL, "consent_version" varchar(20) NOT NULL, "consent_text_hash" varchar(64) NOT NULL, "granted_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "granted_via" varchar(20) NOT NULL, "ip_address" varchar(45), "revoked_at" datetime, "revoked_reason" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_6283f1222bdc2390cf16836ce7d" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('admin_approval_requests',
      `CREATE TABLE "admin_approval_requests" ("request_id" varchar PRIMARY KEY NOT NULL, "requester_id" varchar NOT NULL, "approver_id" varchar, "action" varchar(100) NOT NULL, "resource_type" varchar(50), "resource_id" varchar, "before_value" text, "after_value" text, "status" varchar(20) NOT NULL DEFAULT ('pending'), "requested_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "approved_at" datetime, "rejected_at" datetime, "rejection_reason" text, "execution_error" text, "cancelled_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_c7cf76c85deacb1fb4f2f8db2ff" FOREIGN KEY ("requester_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "admin_approval_requests" ("request_id" varchar PRIMARY KEY NOT NULL, "requester_id" varchar NOT NULL, "approver_id" varchar, "action" varchar(100) NOT NULL, "resource_type" varchar(50), "resource_id" varchar, "before_value" text, "after_value" text, "status" varchar(20) NOT NULL DEFAULT ('pending'), "requested_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "approved_at" datetime, "rejected_at" datetime, "rejection_reason" text, "execution_error" text, "cancelled_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_c7cf76c85deacb1fb4f2f8db2ff" FOREIGN KEY ("requester_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('holding_limits',
      `CREATE TABLE "holding_limits" ("limit_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "limit_type" varchar(20) NOT NULL, "target_symbol" varchar(20), "target_sector" varchar(50), "max_weight" decimal(10,4) NOT NULL, "max_value" decimal(18,4), "action_on_breach" varchar(20) NOT NULL DEFAULT ('warn'), "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime, CONSTRAINT "CHK_max_weight" CHECK (max_weight BETWEEN 0 AND 1), CONSTRAINT "FK_577439eb954be2fbabe5df93b25" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "holding_limits" ("limit_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "limit_type" varchar(20) NOT NULL, "target_symbol" varchar(20), "target_sector" varchar(50), "max_weight" decimal(10,4) NOT NULL, "max_value" decimal(18,4), "action_on_breach" varchar(20) NOT NULL DEFAULT ('warn'), "is_active" boolean NOT NULL DEFAULT true, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime, CONSTRAINT "CHK_max_weight" CHECK (max_weight BETWEEN 0 AND 1), CONSTRAINT "FK_577439eb954be2fbabe5df93b25" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('portfolio_snapshots',
      `CREATE TABLE "portfolio_snapshots" ("snapshot_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "snapshot_date" date NOT NULL, "total_market_value" decimal(18,4), "total_cost" decimal(18,4), "daily_return" decimal(10,6), "cumulative_return" decimal(10,6), "total_return" decimal(10,6), "annual_return" decimal(10,6), "volatility" decimal(10,6), "sharpe_ratio" decimal(10,6), "sortino_ratio" decimal(10,6), "max_drawdown" decimal(10,6), "calmar_ratio" decimal(10,6), "treynor_ratio" decimal(10,6), "beta" decimal(10,6), "risk_free_rate" decimal(10,6), "asset_allocation" text, "sector_allocation" text, "holdings_snapshot" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_de294421d3b9ba2ba8dc665badd" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "portfolio_snapshots" ("snapshot_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "snapshot_date" date NOT NULL, "total_market_value" decimal(18,4), "total_cost" decimal(18,4), "daily_return" decimal(10,6), "cumulative_return" decimal(10,6), "total_return" decimal(10,6), "annual_return" decimal(10,6), "volatility" decimal(10,6), "sharpe_ratio" decimal(10,6), "sortino_ratio" decimal(10,6), "max_drawdown" decimal(10,6), "calmar_ratio" decimal(10,6), "treynor_ratio" decimal(10,6), "beta" decimal(10,6), "risk_free_rate" decimal(10,6), "asset_allocation" text, "sector_allocation" text, "holdings_snapshot" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_de294421d3b9ba2ba8dc665badd" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('market_risk_alert_acknowledgments',
      `CREATE TABLE "market_risk_alert_acknowledgments" ("id" varchar PRIMARY KEY NOT NULL, "alert_id" varchar NOT NULL, "user_id" varchar NOT NULL, "acknowledged_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_39e4731704256c44d4c9a8031ab" FOREIGN KEY ("alert_id") REFERENCES "market_risk_alerts" ("alert_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_04f3d060e4741793a1cd3903343" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "market_risk_alert_acknowledgments" ("id" varchar PRIMARY KEY NOT NULL, "alert_id" varchar NOT NULL, "user_id" varchar NOT NULL, "acknowledged_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_39e4731704256c44d4c9a8031ab" FOREIGN KEY ("alert_id") REFERENCES "market_risk_alerts" ("alert_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_04f3d060e4741793a1cd3903343" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('data_export_requests',
      `CREATE TABLE "data_export_requests" ("export_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "format" varchar(20) NOT NULL, "include_tables" text, "file_path" varchar(500), "file_size" bigint, "checksum" varchar(64), "status" varchar(20) NOT NULL DEFAULT ('pending'), "error_message" text, "expires_at" datetime NOT NULL, "generated_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_df32d2c16d5db8fca41c2f2f066" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "data_export_requests" ("export_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "format" varchar(20) NOT NULL, "include_tables" text, "file_path" varchar(500), "file_size" bigint, "checksum" varchar(64), "status" varchar(20) NOT NULL DEFAULT ('pending'), "error_message" text, "expires_at" datetime NOT NULL, "generated_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_df32d2c16d5db8fca41c2f2f066" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('financial_data',
      `CREATE TABLE "financial_data" ("financial_id" varchar PRIMARY KEY NOT NULL, "stock_id" varchar NOT NULL, "report_period" varchar(10) NOT NULL, "report_type" varchar(10) NOT NULL DEFAULT ('annual'), "revenue" decimal(18,2), "net_profit" decimal(18,2), "operating_profit" decimal(18,2), "total_assets" decimal(18,2), "total_liabilities" decimal(18,2), "shareholders_equity" decimal(18,2), "operating_cash_flow" decimal(18,2), "free_cash_flow" decimal(18,2), "eps" decimal(10,4), "book_value_per_share" decimal(10,4), "dividend_per_share" decimal(10,4), "roe" decimal(10,4), "roa" decimal(10,4), "debt_to_equity" decimal(10,4), "current_ratio" decimal(10,4), "pe_ratio" decimal(10,4), "pb_ratio" decimal(10,4), "ps_ratio" decimal(10,4), "ev_ebitda" decimal(10,4), "revenue_growth_yoy" decimal(10,4), "profit_growth_yoy" decimal(10,4), "metadata" text NOT NULL DEFAULT ('{}'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_5ff00dfe35d5cf8e93a2d3bfdf8" UNIQUE ("stock_id", "report_period", "report_type"), CONSTRAINT "FK_d87dd56d0e9dc85a0c1917b1929" FOREIGN KEY ("stock_id") REFERENCES "stocks" ("stock_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "financial_data" ("financial_id" varchar PRIMARY KEY NOT NULL, "stock_id" varchar NOT NULL, "report_period" varchar(10) NOT NULL, "report_type" varchar(10) NOT NULL DEFAULT ('annual'), "revenue" decimal(18,2), "net_profit" decimal(18,2), "operating_profit" decimal(18,2), "total_assets" decimal(18,2), "total_liabilities" decimal(18,2), "shareholders_equity" decimal(18,2), "operating_cash_flow" decimal(18,2), "free_cash_flow" decimal(18,2), "eps" decimal(10,4), "book_value_per_share" decimal(10,4), "dividend_per_share" decimal(10,4), "roe" decimal(10,4), "roa" decimal(10,4), "debt_to_equity" decimal(10,4), "current_ratio" decimal(10,4), "pe_ratio" decimal(10,4), "pb_ratio" decimal(10,4), "ps_ratio" decimal(10,4), "ev_ebitda" decimal(10,4), "revenue_growth_yoy" decimal(10,4), "profit_growth_yoy" decimal(10,4), "metadata" text NOT NULL DEFAULT ('{}'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_5ff00dfe35d5cf8e93a2d3bfdf8" UNIQUE ("stock_id", "report_period", "report_type"), CONSTRAINT "FK_d87dd56d0e9dc85a0c1917b1929" FOREIGN KEY ("stock_id") REFERENCES "stocks" ("stock_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('valuation_records',
      `CREATE TABLE "valuation_records" ("valuation_id" varchar PRIMARY KEY NOT NULL, "stock_id" varchar NOT NULL, "user_id" varchar, "method" varchar(20) NOT NULL, "inputs" text NOT NULL DEFAULT ('{}'), "result_value" decimal(18,4), "result_range_low" decimal(18,4), "result_range_high" decimal(18,4), "confidence_level" decimal(5,4), "assumptions" text NOT NULL DEFAULT ('{}'), "sensitivity_analysis" text NOT NULL DEFAULT ('{}'), "status" varchar(20) NOT NULL DEFAULT ('completed'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_a37f89ec26187ee80c71c5ff64e" FOREIGN KEY ("stock_id") REFERENCES "stocks" ("stock_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_65275b7f30d3a84573b1699b448" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE SET NULL ON UPDATE NO ACTION)`,
      `CREATE TABLE "valuation_records" ("valuation_id" varchar PRIMARY KEY NOT NULL, "stock_id" varchar NOT NULL, "user_id" varchar, "method" varchar(20) NOT NULL, "inputs" text NOT NULL DEFAULT ('{}'), "result_value" decimal(18,4), "result_range_low" decimal(18,4), "result_range_high" decimal(18,4), "confidence_level" decimal(5,4), "assumptions" text NOT NULL DEFAULT ('{}'), "sensitivity_analysis" text NOT NULL DEFAULT ('{}'), "status" varchar(20) NOT NULL DEFAULT ('completed'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_a37f89ec26187ee80c71c5ff64e" FOREIGN KEY ("stock_id") REFERENCES "stocks" ("stock_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_65275b7f30d3a84573b1699b448" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE SET NULL ON UPDATE NO ACTION)`);

    addTable('alert_rules',
      `CREATE TABLE "alert_rules" ("rule_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "rule_name" varchar(100) NOT NULL, "rule_type" varchar(20) NOT NULL, "monitor_type" varchar(20) NOT NULL, "threshold" decimal(18,6) NOT NULL, "operator" varchar(10) NOT NULL DEFAULT ('>'), "status" varchar(20) NOT NULL DEFAULT ('active'), "notification_config" text NOT NULL DEFAULT ('{}'), "rules" text NOT NULL DEFAULT ('{}'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_50b6fe6b7247a43c503f0ccd4c3" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_28f424f9442043318dd4f8a4f58" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`,
      `CREATE TABLE "alert_rules" ("rule_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "rule_name" varchar(100) NOT NULL, "rule_type" varchar(20) NOT NULL, "monitor_type" varchar(20) NOT NULL, "threshold" decimal(18,6) NOT NULL, "operator" varchar(10) NOT NULL DEFAULT ('>'), "status" varchar(20) NOT NULL DEFAULT ('active'), "notification_config" text NOT NULL DEFAULT ('{}'), "rules" text NOT NULL DEFAULT ('{}'), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_50b6fe6b7247a43c503f0ccd4c3" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_28f424f9442043318dd4f8a4f58" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);

    addTable('monitor_snapshots',
      `CREATE TABLE "monitor_snapshots" ("snapshot_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "monitor_type" varchar(50), "metric_value" decimal(18,6), "threshold_value" decimal(18,6), "operator" varchar(10), "holdings_risk" text, "extra_metrics" text, "snapshot_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_eea4e954813b4d1060040ed09cc" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "monitor_snapshots" ("snapshot_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "monitor_type" varchar(50), "metric_value" decimal(18,6), "threshold_value" decimal(18,6), "operator" varchar(10), "holdings_risk" text, "extra_metrics" text, "snapshot_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_eea4e954813b4d1060040ed09cc" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('stop_loss_suggestions',
      `CREATE TABLE "stop_loss_suggestions" ("suggestion_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "confidence_level" decimal(5,4) NOT NULL, "time_horizon" integer NOT NULL DEFAULT (1), "dimension" varchar(20) NOT NULL, "basis" varchar(30) NOT NULL, "suggestions" text NOT NULL, "disclaimer" text NOT NULL, "triggered_count" integer NOT NULL DEFAULT (0), "last_triggered_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_784f233df4fab0deaabd1c23d5a" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b47185f447fcfbdf2d9acaa1143" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "stop_loss_suggestions" ("suggestion_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "confidence_level" decimal(5,4) NOT NULL, "time_horizon" integer NOT NULL DEFAULT (1), "dimension" varchar(20) NOT NULL, "basis" varchar(30) NOT NULL, "suggestions" text NOT NULL, "disclaimer" text NOT NULL, "triggered_count" integer NOT NULL DEFAULT (0), "last_triggered_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_784f233df4fab0deaabd1c23d5a" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b47185f447fcfbdf2d9acaa1143" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('risk_events',
      `CREATE TABLE "risk_events" ("event_id" varchar PRIMARY KEY NOT NULL, "source_id" varchar NOT NULL, "source_type" varchar(30) NOT NULL, "external_id" varchar(255), "title" varchar(500) NOT NULL, "summary" text, "content" text, "url" varchar(1000), "level" varchar(20) NOT NULL, "symbols" text, "sectors" text, "macro_tags" text, "occurred_at" datetime NOT NULL, "fetched_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "is_processed" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_37878e71186ac1382f36181ea32" FOREIGN KEY ("source_id") REFERENCES "risk_event_sources" ("source_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "risk_events" ("event_id" varchar PRIMARY KEY NOT NULL, "source_id" varchar NOT NULL, "source_type" varchar(30) NOT NULL, "external_id" varchar(255), "title" varchar(500) NOT NULL, "summary" text, "content" text, "url" varchar(1000), "level" varchar(20) NOT NULL, "symbols" text, "sectors" text, "macro_tags" text, "occurred_at" datetime NOT NULL, "fetched_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "is_processed" boolean NOT NULL DEFAULT false, CONSTRAINT "FK_37878e71186ac1382f36181ea32" FOREIGN KEY ("source_id") REFERENCES "risk_event_sources" ("source_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('risk_event_impacts',
      `CREATE TABLE "risk_event_impacts" ("impact_id" varchar PRIMARY KEY NOT NULL, "event_id" varchar NOT NULL, "user_id" varchar NOT NULL, "portfolio_id" varchar NOT NULL, "holding_id" varchar, "symbol" varchar(20), "impact_level" varchar(20) NOT NULL, "impact_summary" text, "portfolio_weight" decimal(10,6), "is_notified" boolean NOT NULL DEFAULT (0), "notified_at" datetime, "is_read" boolean NOT NULL DEFAULT (0), "read_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_718aaff0ac3fbee5ba790c9acb8" FOREIGN KEY ("event_id") REFERENCES "risk_events" ("event_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_99e83e00f48a4fa831f47f2746b" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_020fc6f07a6a09f3a2ca8934bf1" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_5bb7b5914abefd8ad2ed0c0d9a4" FOREIGN KEY ("holding_id") REFERENCES "holdings" ("holding_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "risk_event_impacts" ("impact_id" varchar PRIMARY KEY NOT NULL, "event_id" varchar NOT NULL, "user_id" varchar NOT NULL, "portfolio_id" varchar NOT NULL, "holding_id" varchar, "symbol" varchar(20), "impact_level" varchar(20) NOT NULL, "impact_summary" text, "portfolio_weight" decimal(10,6), "is_notified" boolean NOT NULL DEFAULT false, "notified_at" datetime, "is_read" boolean NOT NULL DEFAULT false, "read_at" datetime, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_718aaff0ac3fbee5ba790c9acb8" FOREIGN KEY ("event_id") REFERENCES "risk_events" ("event_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_99e83e00f48a4fa831f47f2746b" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_020fc6f07a6a09f3a2ca8934bf1" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_5bb7b5914abefd8ad2ed0c0d9a4" FOREIGN KEY ("holding_id") REFERENCES "holdings" ("holding_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('holding_import_tasks',
      `CREATE TABLE "holding_import_tasks" ("task_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "file_name" varchar(255) NOT NULL, "file_path" varchar(500), "file_size" integer, "format" varchar(10) NOT NULL, "total_rows" integer NOT NULL DEFAULT (0), "valid_rows" integer NOT NULL DEFAULT (0), "error_rows" integer NOT NULL DEFAULT (0), "status" varchar(20) NOT NULL DEFAULT ('pending'), "error_message" text, "triggered_var" boolean NOT NULL DEFAULT (0), "triggered_stress" boolean NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "completed_at" datetime, CONSTRAINT "FK_47092d98b14ccf4ae83d5d94325" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_971db75734142a934758a003a9b" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "holding_import_tasks" ("task_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "file_name" varchar(255) NOT NULL, "file_path" varchar(500), "file_size" integer, "format" varchar(10) NOT NULL, "total_rows" integer NOT NULL DEFAULT (0), "valid_rows" integer NOT NULL DEFAULT (0), "error_rows" integer NOT NULL DEFAULT (0), "status" varchar(20) NOT NULL DEFAULT ('pending'), "error_message" text, "triggered_var" boolean NOT NULL DEFAULT false, "triggered_stress" boolean NOT NULL DEFAULT false, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, "completed_at" datetime, CONSTRAINT "FK_47092d98b14ccf4ae83d5d94325" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_971db75734142a934758a003a9b" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('holding_import_rows',
      `CREATE TABLE "holding_import_rows" ("row_id" varchar PRIMARY KEY NOT NULL, "task_id" varchar NOT NULL, "row_number" integer NOT NULL, "raw_data" text, "parsed_data" text, "is_valid" boolean NOT NULL DEFAULT (0), "error_fields" text, "created_holding_id" varchar, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_6fc744dfa767c6f7bf041b02e6b" FOREIGN KEY ("task_id") REFERENCES "holding_import_tasks" ("task_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_d6497346fa0e5b1f54815327b5b" FOREIGN KEY ("created_holding_id") REFERENCES "holdings" ("holding_id") ON DELETE SET NULL ON UPDATE NO ACTION)`,
      `CREATE TABLE "holding_import_rows" ("row_id" varchar PRIMARY KEY NOT NULL, "task_id" varchar NOT NULL, "row_number" integer NOT NULL, "raw_data" text, "parsed_data" text, "is_valid" boolean NOT NULL DEFAULT false, "error_fields" text, "created_holding_id" varchar, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_6fc744dfa767c6f7bf041b02e6b" FOREIGN KEY ("task_id") REFERENCES "holding_import_tasks" ("task_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_d6497346fa0e5b1f54815327b5b" FOREIGN KEY ("created_holding_id") REFERENCES "holdings" ("holding_id") ON DELETE SET NULL ON UPDATE NO ACTION)`);

    addTable('attribution_results',
      `CREATE TABLE "attribution_results" ("attribution_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "benchmark_type" varchar(30) NOT NULL, "benchmark_config" text, "portfolio_return" decimal(10,6) NOT NULL, "benchmark_return" decimal(10,6) NOT NULL, "excess_return" decimal(10,6) NOT NULL, "allocation_effect" decimal(10,6) NOT NULL, "selection_effect" decimal(10,6) NOT NULL, "interaction_effect" decimal(10,6) NOT NULL, "sector_details" text NOT NULL, "disclaimer" text NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_4a2023c54bc21e89baeb1edde75" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_ffbab10bc7f55cd2e953acddafe" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "attribution_results" ("attribution_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "benchmark_type" varchar(30) NOT NULL, "benchmark_config" text, "portfolio_return" decimal(10,6) NOT NULL, "benchmark_return" decimal(10,6) NOT NULL, "excess_return" decimal(10,6) NOT NULL, "allocation_effect" decimal(10,6) NOT NULL, "selection_effect" decimal(10,6) NOT NULL, "interaction_effect" decimal(10,6) NOT NULL, "sector_details" text NOT NULL, "disclaimer" text NOT NULL, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FK_4a2023c54bc21e89baeb1edde75" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_ffbab10bc7f55cd2e953acddafe" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    addTable('portfolio_analytics',
      `CREATE TABLE "portfolio_analytics" ("analytics_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "analysis_date" date NOT NULL, "total_value" decimal(18,4), "total_return" decimal(10,6), "annual_return" decimal(10,6), "volatility" decimal(10,6), "sharpe_ratio" decimal(10,6), "sortino_ratio" decimal(10,6), "max_drawdown" decimal(10,6), "calmar_ratio" decimal(10,6), "treynor_ratio" decimal(10,6), "beta" decimal(10,6), "risk_free_rate" decimal(10,6), "metrics" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_b0aefa24a883972a130d71e5aac" UNIQUE ("portfolio_id", "analysis_date"), CONSTRAINT "FK_48531b26b8ad9d6574118666a6d" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_8ac27df58d80f1e3e500f84eaaa" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`,
      `CREATE TABLE "portfolio_analytics" ("analytics_id" varchar PRIMARY KEY NOT NULL, "portfolio_id" varchar NOT NULL, "user_id" varchar NOT NULL, "analysis_date" date NOT NULL, "total_value" decimal(18,4), "total_return" decimal(10,6), "annual_return" decimal(10,6), "volatility" decimal(10,6), "sharpe_ratio" decimal(10,6), "sortino_ratio" decimal(10,6), "max_drawdown" decimal(10,6), "calmar_ratio" decimal(10,6), "treynor_ratio" decimal(10,6), "beta" decimal(10,6), "risk_free_rate" decimal(10,6), "metrics" text, "created_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UQ_b0aefa24a883972a130d71e5aac" UNIQUE ("portfolio_id", "analysis_date"), CONSTRAINT "FK_48531b26b8ad9d6574118666a6d" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios" ("portfolio_id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_8ac27df58d80f1e3e500f84eaaa" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION)`);

    for (const { sqlite, pg } of Object.values(tableDefinitions)) {
      await queryRunner.query(isPostgres ? pg : sqlite);
    }

    // 创建索引
    const indexStatements = [
      `CREATE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `,
      `CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `,
      `CREATE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `,
      `CREATE INDEX "IDX_9c98f005249412c8333a3b2c59" ON "users" ("openid") `,
      `CREATE INDEX "IDX_3676155292d72c67cd4e090514" ON "users" ("status") `,
      `CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `,
      `CREATE INDEX "IDX_f1d7436798f0456de71e64360a" ON "optimization_scenarios" ("objective") `,
      `CREATE INDEX "IDX_1a409f09bdc0d43788bb39af2d" ON "help_content" ("topic") `,
      `CREATE INDEX "IDX_f1ede6fbc6e83a4e2ecfdac9e2" ON "market_risk_alerts" ("index_symbol") `,
      `CREATE INDEX "IDX_a7e5bb181049706621d348c904" ON "market_risk_alert_templates" ("index_symbol") `,
      `CREATE INDEX "IDX_d3c88017b73e94570da37042d1" ON "audit_log_integrity" ("log_id") `,
      `CREATE INDEX "IDX_fc5af9fb82dbb8d0afe1076caf" ON "user_login_history" ("user_id") `,
      `CREATE INDEX "IDX_03f9606e93f9805943eff2bec8" ON "market_data" ("symbol") `,
      `CREATE INDEX "IDX_be6b3945a1870177d2435f92af" ON "market_data" ("trade_date") `,
      `CREATE INDEX "IDX_c12c6b475046eae01e01b0995f" ON "tool_var_history" ("user_id") `,
      `CREATE INDEX "IDX_abdd997b009437486baf753185" ON "stocks" ("symbol") `,
      `CREATE INDEX "IDX_87f8c2a7c997987833a65f603c" ON "partition_metadata" ("table_type") `,
      `CREATE INDEX "IDX_33741ccc88daf4a6ac9524d415" ON "computation_cache" ("expires_at") `,
      `CREATE INDEX "IDX_0c39c9074fffd1a0fd9d52ab91" ON "computation_cache" ("computation_type", "param_hash") `,
      `CREATE INDEX "IDX_96176994010dd1e7b6b25bf3a3" ON "market_snapshot_cache" ("expires_at") `,
      `CREATE INDEX "IDX_80e3ff474e6332e5d3efd0100b" ON "portfolio_summary_cache" ("expires_at") `,
      `CREATE INDEX "IDX_0109eeb9a9e58a2ffe58b550ab" ON "message_queue" ("priority", "scheduled_at") `,
      `CREATE INDEX "IDX_3cb0a8237422ac32573ac9c193" ON "message_queue" ("queue_name", "status", "scheduled_at") `,
      `CREATE INDEX "IDX_815ccd746de6fa202ce06865a6" ON "refresh_token_blacklist" ("expires_at") `,
      `CREATE INDEX "IDX_566f927f33d05834c37dc4fe5d" ON "risk_event_sources" ("source_type") `,
      `CREATE INDEX "IDX_8b368eb3887e80819ad9db2bf4" ON "market_volatility_indices" ("index_symbol") `,
      `CREATE INDEX "IDX_1d919d453d587e650c418a87e5" ON "market_volatility_history" ("index_symbol") `,
      `CREATE INDEX "IDX_621e5a71c5985b1dd7570dbaa1" ON "portfolio_templates" ("risk_level") `,
      `CREATE INDEX "IDX_e95336b5d52274ace32bb8ca69" ON "portfolio_templates" ("sort_order") `,
      `CREATE INDEX "IDX_afb483fdde790df420ad10598b" ON "video_tutorials" ("topic") `,
      `CREATE INDEX "IDX_8ccab3215ac4cd4e4087785611" ON "video_tutorials" ("category") `,
      `CREATE INDEX "IDX_e9658e959c490b0a634dfc5478" ON "user_sessions" ("user_id") `,
      `CREATE INDEX "IDX_2f4f9915c4b755588d01fee50b" ON "holdings" ("portfolio_id") `,
      `CREATE INDEX "IDX_810371762a3a984e96034a4d1f" ON "holdings" ("symbol") `,
      `CREATE INDEX "IDX_7b19bde76cbd93588cfb31b2d9" ON "holdings" ("status") `,
      `CREATE INDEX "IDX_57fba72db5ac40768b40f0ecfa" ON "portfolios" ("user_id") `,
      `CREATE INDEX "IDX_29f7b2bcfa0d26fa6699015037" ON "portfolios" ("name") `,
      `CREATE INDEX "IDX_a4866b07151564e3823cdcc520" ON "portfolios" ("type") `,
      `CREATE INDEX "IDX_583c255d91f5ae2a0072d1c056" ON "portfolios" ("status") `,
      `CREATE INDEX "IDX_3f73a5e0905a80144ee6b9f959" ON "optimization_results" ("portfolio_id") `,
      `CREATE INDEX "IDX_943dcd0da808a19aca09781ef6" ON "optimization_results" ("user_id") `,
      `CREATE INDEX "IDX_c4f0c0484ab699dd60bea01602" ON "var_components" ("var_id") `,
      `CREATE INDEX "IDX_6283f1222bdc2390cf16836ce7" ON "user_consents" ("user_id") `,
      `CREATE INDEX "IDX_fc51c44e296132242ed415f181" ON "user_consents" ("consent_type") `,
      `CREATE INDEX "IDX_c7cf76c85deacb1fb4f2f8db2f" ON "admin_approval_requests" ("requester_id") `,
      `CREATE INDEX "IDX_577439eb954be2fbabe5df93b2" ON "holding_limits" ("portfolio_id") `,
      `CREATE INDEX "IDX_de294421d3b9ba2ba8dc665bad" ON "portfolio_snapshots" ("portfolio_id") `,
      `CREATE INDEX "IDX_39e4731704256c44d4c9a8031a" ON "market_risk_alert_acknowledgments" ("alert_id") `,
      `CREATE INDEX "IDX_04f3d060e4741793a1cd390334" ON "market_risk_alert_acknowledgments" ("user_id") `,
      `CREATE INDEX "IDX_df32d2c16d5db8fca41c2f2f06" ON "data_export_requests" ("user_id") `,
      `CREATE INDEX "IDX_d87dd56d0e9dc85a0c1917b192" ON "financial_data" ("stock_id") `,
      `CREATE INDEX "IDX_a37f89ec26187ee80c71c5ff64" ON "valuation_records" ("stock_id") `,
      `CREATE INDEX "IDX_65275b7f30d3a84573b1699b44" ON "valuation_records" ("user_id") `,
      `CREATE INDEX "IDX_39c6535ae292e6c0cace46144c" ON "valuation_records" ("method") `,
      `CREATE INDEX "IDX_eea4e954813b4d1060040ed09c" ON "monitor_snapshots" ("portfolio_id") `,
      `CREATE INDEX "IDX_784f233df4fab0deaabd1c23d5" ON "stop_loss_suggestions" ("portfolio_id") `,
      `CREATE INDEX "IDX_b47185f447fcfbdf2d9acaa114" ON "stop_loss_suggestions" ("user_id") `,
      `CREATE INDEX "IDX_37878e71186ac1382f36181ea3" ON "risk_events" ("source_id") `,
      `CREATE INDEX "IDX_718aaff0ac3fbee5ba790c9acb" ON "risk_event_impacts" ("event_id") `,
      `CREATE INDEX "IDX_99e83e00f48a4fa831f47f2746" ON "risk_event_impacts" ("user_id") `,
      `CREATE INDEX "IDX_020fc6f07a6a09f3a2ca8934bf" ON "risk_event_impacts" ("portfolio_id") `,
      `CREATE INDEX "IDX_47092d98b14ccf4ae83d5d9432" ON "holding_import_tasks" ("portfolio_id") `,
      `CREATE INDEX "IDX_971db75734142a934758a003a9" ON "holding_import_tasks" ("user_id") `,
      `CREATE INDEX "IDX_6fc744dfa767c6f7bf041b02e6" ON "holding_import_rows" ("task_id") `,
      `CREATE INDEX "IDX_4a2023c54bc21e89baeb1edde7" ON "attribution_results" ("portfolio_id") `,
      `CREATE INDEX "IDX_ffbab10bc7f55cd2e953acddaf" ON "attribution_results" ("user_id") `,
      `CREATE INDEX "IDX_48531b26b8ad9d6574118666a6" ON "portfolio_analytics" ("portfolio_id") `,
      `CREATE INDEX "IDX_8ac27df58d80f1e3e500f84eaa" ON "portfolio_analytics" ("user_id") `
    ];
    for (const stmt of indexStatements) {
      await queryRunner.query(stmt);
    }

    if (!isPostgres) {
      await queryRunner.query('PRAGMA foreign_keys = ON');
    }

    console.log('InitialSchema1718000000001 migration completed successfully');
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    const isPostgres = getDbType() === 'postgres';
    if (!isPostgres) {
      await queryRunner.query('PRAGMA foreign_keys = OFF');
    }

    // 按创建顺序反向删除表
    const tablesToDrop = [
      'portfolio_analytics',
      'attribution_results',
      'holding_import_rows',
      'holding_import_tasks',
      'risk_event_impacts',
      'risk_events',
      'stop_loss_suggestions',
      'monitor_snapshots',
      'alert_rules',
      'valuation_records',
      'financial_data',
      'data_export_requests',
      'market_risk_alert_acknowledgments',
      'portfolio_snapshots',
      'holding_limits',
      'admin_approval_requests',
      'user_consents',
      'var_components',
      'optimization_results',
      'portfolios',
      'reports',
      'stress_tests',
      'var_calculations',
      'holdings',
      'audit_logs',
      'user_sessions',
      'orders',
      'alert_history',
      'monitor_configs',
      'video_tutorials',
      'portfolio_templates',
      'market_volatility_history',
      'market_volatility_indices',
      'risk_event_sources',
      'refresh_token_blacklist',
      'message_queue',
      'portfolio_summary_cache',
      'market_snapshot_cache',
      'computation_cache',
      'partition_metadata',
      'stocks',
      'system_configs',
      'subscription_plans',
      'tool_var_history',
      'market_data',
      'user_login_history',
      'audit_log_integrity',
      'anonymization_logs',
      'market_risk_alert_templates',
      'market_risk_alerts',
      'help_content',
      'stress_scenarios',
      'optimization_scenarios',
      'users',
    ];

    for (const table of tablesToDrop) {
      try {
        await queryRunner.query(`DROP TABLE IF EXISTS "${table}"`);
      } catch (e: any) {
        console.warn(`Failed to drop table ${table}: ${e.message}`);
      }
    }

    if (!isPostgres) {
      await queryRunner.query('PRAGMA foreign_keys = ON');
    }

    console.log('InitialSchema1718000000001 rollback completed');
  }
}
